language: python
os: linux
python:
- '3.8'
install:
- pip install -r requirements.txt
before_script: python -m incremental.update manafa --patch
script: pytest manafa/tests
notifications:
  email:
  - rui.rrua@gmail.com
deploy:
  provider: pypi
  username: __token__
  password:
    secure: "cGZ6TsRm5QM/nWjdwNJAWcxbX+V3NlPgxKjeW5cWJypDYpHtFM62d7ckIe1oHu5NQxQm47/MO8iCUEdLfQmE5e1/gKmC7kjitJNXkeBnC0TIMVzkANTfX2a6Pl+hlqNpdjBo1Mnt20L5NqkF5DnLm7p1xrIo7SEvtfejUR0O2wmTSkBjnXf1h8ecf2YBw1k7rsNF39YhAoTPXsakYXtHX4nX7FlwTbR0UdeN8zHKXcWeE96SLbn6yFdRDn2sc2ClpkuaeSUeE6gKL2UYPr0FK8A8lFpR2ZBGp35IcbvuWOjQp+BLzpmBnkl7hfTEAS4zzQUsjxzjtpbDVYcEpW/WmXeTXVuzhwwRa59sGAqex0g4dUg1KEkS9u6XaEiO5YcAWFUOYSBhAFqGMJXpSGNsPZVCDRFCYqT1TFyxLlWgZ0cKSDfTROqYLCEiMD6/BAWl57hjiKy1PSlQRhEJKHArl0uppAQZSd+HdW/ayXQy2q/nzoC7kULd9g3J6NgWiCMfbqyMW0qA6IoqJtG09aXFpaCBwMXbcS+63567m5AnMGzf5RfEEeRO10FJhp4eSVHl0AsdjSk271QJl8GyOo4W1g8pOU6gW2UNQaziIxTGGg/SVx1waq2YNe0GcqJ8B2ylgPmQbZcVf5oQCRJCESMJOhqRXQcFuknYJFDNCcy5ucY="
  on:
    branch: main
  distributions: sdist
